--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: jenkins
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: jenkins
  template: 
    metadata: 
      labels: 
        app: jenkins
    spec: 
      containers: 
        - 
          env: 
            - 
              name: JAVA_OPTS
              value: "-Djenkins.install.runSetupWizard=false"
          image: "wolfdragon19/jenkins-image:1.0"
          name: jenkins
          ports: 
            - 
              containerPort: 8080
              name: http-port
            - 
              containerPort: 50000
              name: jnlp-port
          volumeMounts: 
            - 
              mountPath: /var/jenkins_home
              name: jenkins-home
      volumes: 
        - 
          emptyDir: {}
          name: jenkins-home

